# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20140827_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50, verbose_name='Triggered Event')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Recipient of the Email')),
                ('domain', models.CharField(max_length=50, verbose_name='Sender domain')),
                ('ip', models.GenericIPAddressField(verbose_name='Recipients IP address')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Recipients Address')),
                ('mailing_list', models.CharField(max_length=200, null=True, verbose_name='Used Mailing List')),
                ('user_agent', models.CharField(max_length=220, null=True, verbose_name='User Agent of the Recipient')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name_plural': 'Emails Statistics',
                'verbose_name': 'Email Stat',
            },
        ),
    ]
