# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_emailrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='address',
            field=models.CharField(max_length=256, null=True, verbose_name='Recipients Address'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='mailing_list',
            field=models.CharField(max_length=128, null=True, verbose_name='Used Mailing List'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='user_agent',
            field=models.CharField(max_length=512, null=True, verbose_name='User Agent of the Recipient'),
        ),
    ]
